### ISSUE TITLE
建议增加手动模式

### ISSUE THREAD

**Issue by xxxxue** [Daydreamer-riri/vscode-ext-packages#2]
这个插件运行起来 笔记本风扇呼呼转,  cpu 飙升
建议增加一个手动模式,  只有用户想要检查的时候才执行

**Comment by Daydreamer-riri** [comment]
插件在没有进行请求版本的时候应该是不会有多少占用的，目前有做持久化缓存，一个仓库第一次打开确实会出现压力增加的情况，我想下一步是可以做并发限制。

目前我还是希望插件能无感运行，暂时不考虑手动检查。

目前我使用`npm-registry-fetch`来获取所有的版本号，这个插件目前应该没有只使用最新版本号的场景？
